---
abstract: "A simple Web::Simple wrapper for GitHub's PostReceive hooks"
author:
  - 'Matt Phillips <mattp@cpan.org>'
build_requires:
  HTTP::Request::Common: 0
  Plack::Test: 0
  Test::More: 0
  Test::Warn: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-GitHub-PostReceiveHook
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  WWW::GitHub::PostReceiveHook:
    file: lib/WWW/GitHub/PostReceiveHook.pm
    version: 0.004
requires:
  Encode: 0
  JSON: 0
  Try::Tiny: 0
  Web::Simple: 0.008
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=WWW-GitHub-PostReceiveHook
  homepage: https://github.com/mattp-/WWW-GitHub-PostReceiveHook
  repository: https://github.com/mattp-/WWW-GitHub-PostReceiveHook.git
version: 0.004
